title: 'Anti-Money Laundering / Countering the Financing of Terrorism Division'
description: 'ACD is a Division in the Ministry of Law in charge of supervising the precious stones and precious metals sector and mitigating Singapore''s exposure to ML/TF risks.'
url: 'https://acd.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
facebook-pixel: 533742290627102
google-tag-manager: GTM-K75DXG8
collections:
    regulation:
        output: true
    compliance:
        output: true
    customers:
        output: true
    regulated-dealers:
        output: true
resources_name: news
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
favicon: /images/mlawfavicon.ico
google-analytics: UA-10405444-19
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
