title: 'Anti-Money Laundering / Countering the Financing of Terrorism Division'
description: 'ACD is a Division in the Ministry of Law in charge of supervising the precious stones and precious metals sector and mitigating Singapore''s exposure to ML/TF risks.'
url: 'https://acd.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
facebook-pixel: 533742290627102
google-tag-manager: GTM-K75DXG8
resources_name: news
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/mlawfavicon.ico
google_analytics: UA-10405444-19
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://isomer-acd-staging.netlify.app
prod: https://isomer-acd-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: '#907051'
  secondary-color: '#b20838'
  media-colors:
    - title: media-color-one
      color: '#907051'
    - title: media-color-two
      color: '#b20838'
    - title: media-color-three
      color: '#b20838'
    - title: media-color-four
      color: '#907051'
    - title: media-color-five
      color: '#b20838'